component: express
name: expressDemo
org: orgDemo
app: appDemo
stage: dev

inputs:
  src: ./dist/
  functionName: expressDemo
  region: ap-guangzhou
  runtime: Nodejs10.15
  exclude:
    - .env
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
